spring.application.name=Less_Energy_G6
spring.jpa.database=postgresql
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost/LessEnergyDB
spring.datasource.username=postgres
spring.datasource.password=admin


jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
