spring.application.name=Less_Energy_G6
spring.jpa.database=postgresql
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://lessenergydb.postgres.database.azure.com:5432/LessEnergy
spring.datasource.username=energy
spring.datasource.password=databaseG6


jwt.secret=UnaClaveJWTExtrememadaEInnecesariamenteLargaPeroSiNoLaPongoSaleExcepcionPorQueTieneQueSerLarga
